### ISSUE TITLE
Polyfill checklist

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/ie-love#1]
- [ ] https://github.com/chuckcarpenter/REM-unit-polyfill
- [ ] https://github.com/pbakaus/transformie
- [ ] https://github.com/saabi/vminpoly
- [ ] https://github.com/10up/flexibility (definitely this one)

**Comment by coliff** [comment]
👍  for Flexibility and the REM unit polyfills.

'IE-Love' would then serve as a good all-in-one polyfill for old IE when using the forthcoming Bootstrap 4 (currently in Alpha).

**Comment by corysimmons** [comment]
@coliff Do you happen to know if flexibility is any good? I think I heard bad things.

**Comment by coliff** [comment]
To be honest, I haven't tried Flexibility yet. I saw reports that 2.0 and onwards was broken, but 1.6 was reported to work ok. Bootstrap v4 Alpha 6 will be available very soon (which has Flexbox as standard) so I'll properly test it out then in IE8 (and IE9) and report back.
